### ISSUE TITLE
How can I make user.authenticated stick

### ISSUE THREAD

**Issue by ODelibalta** [stefanjarina/vue2-jwt-authentication#2]
Thank you for this. It helped me. 

I do not want to have the menu bar (navigation) component in my login screen. I have my menu-bar component in a separate file and I import it under App.vue above my router view tags. I want to show the menu bar component only when the user is authenticated and it works on initial login but if I refresh etc, user goes back to false.

**Comment by stefanjarina** [comment]
Save the token to browser local storage or cookies.
// Save [do this after you authenticate user]
localStorage.setItem("lastname", "Smith");
// Retrieve [do this when you initialize your application/component]
document.getElementById("result").innerHTML = localStorage.getItem("lastname");
// Removal [do this when you logout user]
localStorage.removeItem("lastname");

**Comment by stefanjarina** [comment]
No comment for more than 2 months, therefore closing.
