### ISSUE TITLE
Protected routing not working  

### ISSUE THREAD

**Issue by asadali3** [stefanjarina/vue2-jwt-authentication#4]
hey when i go to http://localhost:8080/#/secretquote  without login it opens which is not possible in the original vue-jwt-authentication so came to conclusion that there is a problem in `  route: {
    beforeEnter() {
      return auth.user.authenticated;
    }
  }`
is not working is there any way to fixing

**Comment by stefanjarina** [comment]
Yup, API indeed changed a bit for route guards, I've updated the code, but in short, replace:
```javascript
route: {
    beforeEnter() {
      return auth.user.authenticated;
    }
  }
```

with

```javascript
beforeRouteEnter(to, from, next) {
  if (auth.user.authenticated) next()
}
```

or simply do `git pull` to fetch my updated code.
Cheers.

**Comment by asadali3** [comment]
thanks man
